language: ruby
sudo: false

rvm:
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
  - jruby-19mode
  - jruby-9.0.0.0

env:
  - ACTIVE_RECORD_BRANCH="master"
  - ACTIVE_RECORD_BRANCH="4-2-stable"
  - ACTIVE_RECORD_BRANCH="4-1-stable"
  - ACTIVE_RECORD_BRANCH="4-0-stable"
  - ACTIVE_RECORD_VERSION="~> 4.2.0"
  - ACTIVE_RECORD_VERSION="~> 4.1.0"
  - ACTIVE_RECORD_VERSION="~> 4.0.0"
  - ACTIVE_RECORD_VERSION="~> 3.2.0"
  - ACTIVE_RECORD_VERSION="~> 3.1.0"

matrix:
  allow_failures:
    - env: ACTIVE_RECORD_BRANCH="master"
    - env: ACTIVE_RECORD_BRANCH="4-2-stable"
    - env: ACTIVE_RECORD_BRANCH="4-1-stable"
    - env: ACTIVE_RECORD_BRANCH="4-0-stable"
  exclude:
    - rvm: "1.9"
      env: ACTIVE_RECORD_BRANCH="master"
    - rvm: "2.0"
      env: ACTIVE_RECORD_BRANCH="master"
    - rvm: "2.1"
      env: ACTIVE_RECORD_BRANCH="master"
    - rvm: jruby-19mode
      env: ACTIVE_RECORD_BRANCH="master"
    - rvm: jruby-9.0.0.0
      env: ACTIVE_RECORD_BRANCH="master"

before_script:
  - "psql -c 'create database pg_search_test;' -U postgres >/dev/null"

script: "bin/rake"

addons:
  code_climate:
    repo_token: 0a0e3e45118bc447e677d52c21d056a5471c4921d54f96ed7b2550d9fc5043ea
