language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode

env:
  - ACTIVE_RECORD_BRANCH="master"
  - ACTIVE_RECORD_BRANCH="4-1-stable"
  - ACTIVE_RECORD_BRANCH="4-0-stable"
  - ACTIVE_RECORD_VERSION="~> 4.1.0"
  - ACTIVE_RECORD_VERSION="~> 4.0.0"
  - ACTIVE_RECORD_VERSION="~> 3.2.0"
  - ACTIVE_RECORD_VERSION="~> 3.1.0"

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - env: ACTIVE_RECORD_BRANCH="master"
    - env: ACTIVE_RECORD_BRANCH="4-1-stable"
    - env: ACTIVE_RECORD_BRANCH="4-0-stable"

before_script:
  - "psql -c 'create database pg_search_test;' -U postgres >/dev/null"

script: "bundle exec rspec spec"
