language: ruby
bundler_args: --binstubs
cache: bundler

rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - jruby-9.2.11.1

env:
  global:
    - CC_TEST_REPORTER_ID=0a0e3e45118bc447e677d52c21d056a5471c4921d54f96ed7b2550d9fc5043ea
  matrix:
    - ACTIVE_RECORD_BRANCH="master"
    - ACTIVE_RECORD_BRANCH="6-0-stable"
    - ACTIVE_RECORD_VERSION="~> 6.0.0"
    - ACTIVE_RECORD_VERSION="~> 5.2.0"


matrix:
  allow_failures:
    - env: ACTIVE_RECORD_BRANCH="master"
    - env: ACTIVE_RECORD_BRANCH="6-0-stable"
  exclude:
    - rvm: 2.4.10
      env: ACTIVE_RECORD_BRANCH="master"
    - rvm: 2.4.10
      env: ACTIVE_RECORD_VERSION="~> 6.0.0"
    - rvm: 2.4.10
      env: ACTIVE_RECORD_BRANCH="6-0-stable"

before_script:
  - psql --version
  - psql -c 'create database pg_search_test;' -U postgres >/dev/null
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: bin/rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

jdk:
  - openjdk8

addons:
  postgresql: "9.6"
